#!/bin/bash
# Copyright (c) 2015 BITPlan GmbH
# WF 2015-10-18

# get the docker machine settings
docker-machine env default
# run the mediawiki image
docker run -it -p 80:80 --net=host bitplan/mediawiki:0.0.1 /bin/bash
